/*
 * generated by Xtext 2.12.0
 */
package com.alexisfacques.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FeatureDiagramStandaloneSetup extends FeatureDiagramStandaloneSetupGenerated {

	def static void doSetup() {
		new FeatureDiagramStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
